#### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 다수결로 결과를 유도하는 모델

In [1]:
import pandas as pd

In [2]:
iris = pd.read_csv('../Data/iris.csv')
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
# feature와 target 분리
iris_data = iris.loc[:,['SepalLength', "SepalWidth", 'PetalLength', 'PetalWidth']]
# iris_data = iris[['SepalLength', "SepalWidth", 'PetalLength', 'PetalWidth']]
iris_target = iris['Name']

iris_target

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: object

In [9]:
# Data 크기 확인
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

#### Train과 Test 분리

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        iris_data,
        iris_target,
        random_state= 42,
        stratify= iris_target
    )

In [14]:
print(train_input)
print(test_input)
print(train_target)
print(test_target)

     SepalLength  SepalWidth  PetalLength  PetalWidth
130          7.4         2.8          6.1         1.9
122          7.7         2.8          6.7         2.0
81           5.5         2.4          3.7         1.0
71           6.1         2.8          4.0         1.3
89           5.5         2.5          4.0         1.3
..           ...         ...          ...         ...
49           5.0         3.3          1.4         0.2
21           5.1         3.7          1.5         0.4
45           4.8         3.0          1.4         0.3
92           5.8         2.6          4.0         1.2
47           4.6         3.2          1.4         0.2

[112 rows x 4 columns]
     SepalLength  SepalWidth  PetalLength  PetalWidth
42           4.4         3.2          1.3         0.2
56           6.3         3.3          4.7         1.6
99           5.7         2.8          4.1         1.3
53           5.5         2.3          4.0         1.3
38           4.4         3.0          1.3         0.2
85           6.0         3.4          4.5         1.6
134          6.1         2.6          5.6         1.4
141          6.9         3.1          5.1         2.3
107          7.3         2.9          6.3         1.8
132          6.4         2.8          5.6         2.2
106          4.9         2.5          4.5         1.7
140          6.7         3.1          5.6         2.4
69           5.6         2.5          3.9         1.1
84           5.4         3.0          4.5         1.5
18           5.7         3.8          1.7         0.3
10           5.4         3.7          1.5         0.2
20           5.4         3.4          1.7         0.2
63           6.1         2.9          4.7         1.4
14           5.8         4.0          1.2         0.2
96           5.7         2.9          4.2         1.3
147          6.5         3.0          5.2         2.0
93           5.0         2.3          3.3         1.0
138          6.0         3.0          4.8         1.8
51           6.4         3.2          4.5         1.5
116          6.5         3.0          5.5         1.8
57           4.9         2.4          3.3         1.0
41           4.5         2.3          1.3         0.3
127          6.1         3.0          4.9         1.8
7            5.0         3.4          1.5         0.2
77           6.7         3.0          5.0         1.7
108          6.7         2.5          5.8         1.8
104          6.5         3.0          5.8         2.2
22           4.6         3.6          1.0         0.2
28           5.2         3.4          1.4         0.2
35           5.0         3.2          1.2         0.2
23           5.1         3.3          1.7         0.5
148          6.2         3.4          5.4         2.3
66           5.6         3.0          4.5         1.5
130     Iris-virginica
122     Iris-virginica
81     Iris-versicolor
71     Iris-versicolor
89     Iris-versicolor
            ...
49         Iris-setosa
21         Iris-setosa
45         Iris-setosa
92     Iris-versicolor
47         Iris-setosa
Name: Name, Length: 112, dtype: object
42         Iris-setosa
56     Iris-versicolor
99     Iris-versicolor
53     Iris-versicolor
38         Iris-setosa
85     Iris-versicolor
134     Iris-virginica
141     Iris-virginica
107     Iris-virginica
132     Iris-virginica
106     Iris-virginica
140     Iris-virginica
69     Iris-versicolor
84     Iris-versicolor
18         Iris-setosa
10         Iris-setosa
20         Iris-setosa
63     Iris-versicolor
14         Iris-setosa
96     Iris-versicolor
147     Iris-virginica
93     Iris-versicolor
138     Iris-virginica
51     Iris-versicolor
116     Iris-virginica
57     Iris-versicolor
41         Iris-setosa
127     Iris-virginica
7          Iris-setosa
77     Iris-versicolor
108     Iris-virginica
104     Iris-virginica
22         Iris-setosa
28         Iris-setosa
35         Iris-setosa
23         Iris-setosa
148     Iris-virginica
66     Iris-versicolor
Name: Name, dtype: object

#### RandomForest로 분류

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
# 모델 만들기
clf = RandomForestClassifier()

In [17]:
# 학습
clf.fit(train_input, train_target)

RandomForestClassifier()

In [18]:
clf.score(test_input, test_target)

0.8947368421052632

----
#### 독버섯과 관련된 데이터를 사용한 머신러닝
- 8124 종류 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋
- 버섯의 특징을 기반으로 독버섯 유무 판단

In [19]:
# 데이터 획득하기
import urllib.request as req

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)

('../Data/mushroom.csv', <http.client.HTTPMessage at 0x1d6b6e0bb10>)

#### 랜덤포레스트를 디용한 버섯 분류

In [20]:
import pandas as pd

In [24]:
mr = pd.read_csv('../Data/mushroom.csv', header= None)     # header를 지정 안해주면 첫 줄이 column명으로 들어감
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [25]:
mr.shape

(8124, 23)

- 한 줄이 버섯 한 종류
- 첫번째 열 : p(독버섯), e(식용버섯)        -> 얘가 target임
- 두번째 열 : 버섯의 머리 모양 -> b(종), c(원뿔), x(볼록), f(평평), k(혹), s(오목)
- 네번째 열 : 버섯의 머리 색깔 -> n(갈색), b(황갈색), c(연한갈색)

In [26]:
mr[0].unique()

array(['p', 'e'], dtype=object)

#### Feature Data가 알파벳 1자리 문자 -> 숫자로 변환

----
#### 연습

In [30]:
# 알파벳 -> ASCII
ord('x')

120

In [28]:
# ASCII -> 알파벳
chr(120)

'x'

In [32]:
# mr의 1번 컬럼을 숫자로 변경
[ord(i) for i in mr.loc[:, 1]]

[120,
 120,
 98,
 120,
 120,
 120,
 98,
 98,
 120,
 98,
 120,
 120,
 98,
 120,
 120,
 115,
 102,
 120,
 120,
 120,
 98,
 120,
 98,
 98,
 98,
 102,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 115,
 120,
 120,
 98,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 120,
 120,
 98,
 120,
 120,
 98,
 102,
 98,
 120,
 120,
 115,
 98,
 98,
 98,
 98,
 102,
 120,
 102,
 120,
 120,
 102,
 98,
 102,
 120,
 98,
 102,
 120,
 102,
 120,
 102,
 120,
 120,
 102,
 120,
 120,
 120,
 98,
 120,
 102,
 115,
 120,
 98,
 120,
 120,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 98,
 102,
 120,
 98,
 120,
 120,
 98,
 98,
 120,
 120,
 115,
 120,
 120,
 120,
 120,
 115,
 120,
 120,
 115,
 120,
 120,
 102,
 102,
 120,
 120,
 98,
 102,
 120,
 98,
 98,
 98,
 102,
 120,
 102,
 120,
 102,
 120,
 120,
 98,
 120,
 98,
 115,
 102,
 120,
 120,
 102,
 120,
 98,
 98,
 120,
 120,
 120,
 115,
 120,
 120,
 98,
 120,
 98,
 98,
 98,
 98,
 120,
 102,
 120,
 102,
 98,
 98,
 120,
 98,
 120,
 98,
 120,
 98,
 102,
 98,
 98,
 98,
 120,
 98,
 120,
 115,
 102,
 120,
 102,
 120,
 98,
 102,
 98,
 120,
 120,
 120,
 98,
 102,
 120,
 102,
 98,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 102,
 120,
 98,
 98,
 98,
 98,
 120,
 98,
 120,
 120,
 102,
 98,
 120,
 120,
 120,
 115,
 120,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 102,
 98,
 120,
 120,
 98,
 120,
 102,
 102,
 120,
 120,
 120,
 102,
 120,
 120,
 120,
 102,
 120,
 102,
 120,
 115,
 98,
 98,
 98,
 102,
 120,
 98,
 98,
 102,
 120,
 120,
 120,
 102,
 102,
 102,
 120,
 98,
 102,
 120,
 102,
 120,
 120,
 102,
 120,
 102,
 120,
 102,
 120,
 120,
 98,
 115,
 120,
 98,
 102,
 98,
 98,
 120,
 102,
 120,
 98,
 120,
 98,
 120,
 98,
 120,
 120,
 102,
 120,
 120,
 98,
 120,
 98,
 120,
 120,
 98,
 120,
 102,
 120,
 120,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 120,
 102,
 120,
 102,
 120,
 98,
 120,
 98,
 120,
 120,
 98,
 98,
 120,
 98,
 98,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 102,
 98,
 120,
 120,
 120,
 102,
 120,
 102,
 102,
 98,
 98,
 120,
 115,
 102,
 120,
 120,
 120,
 120,
 120,
 102,
 102,
 120,
 102,
 120,
 120,
 98,
 120,
 120,
 102,
 120,
 115,
 120,
 98,
 115,
 98,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 120,
 98,
 120,
 98,
 120,
 98,
 120,
 102,
 120,
 120,
 120,
 120,
 120,
 98,
 98,
 120,
 98,
 120,
 120,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 102,
 120,
 98,
 120,
 102,
 120,
 120,
 102,
 98,
 120,
 102,
 120,
 120,
 98,
 98,
 102,
 98,
 120,
 120,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 98,
 120,
 120,
 98,
 98,
 120,
 98,
 120,
 98,
 98,
 102,
 102,
 120,
 102,
 98,
 120,
 120,
 102,
 120,
 120,
 98,
 102,
 120,
 120,
 102,
 115,
 102,
 102,
 120,
 98,
 120,
 98,
 98,
 98,
 102,
 102,
 102,
 102,
 120,
 115,
 120,
 120,
 102,
 102,
 120,
 102,
 120,
 98,
 102,
 102,
 120,
 98,
 120,
 98,
 120,
 98,
 98,
 120,
 120,
 102,
 120,
 102,
 102,
 98,
 120,
 115,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 98,
 102,
 120,
 102,
 98,
 102,
 120,
 120,
 102,
 120,
 120,
 120,
 102,
 102,
 120,
 98,
 115,
 120,
 102,
 120,
 102,
 120,
 120,
 102,
 120,
 98,
 102,
 120,
 120,
 102,
 120,
 120,
 102,
 120,
 102,
 120,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 102,
 120,
 98,
 120,
 102,
 120,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 120,
 115,
 102,
 115,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 98,
 98,
 120,
 120,
 120,
 120,
 102,
 102,
 98,
 98,
 120,
 102,
 120,
 102,
 102,
 120,
 102,
 120,
 120,
 98,
 102,
 98,
 98,
 115,
 102,
 98,
 120,
 102,
 102,
 120,
 102,
 115,
 98,
 98,
 102,
 98,
 120,
 120,
 120,
 98,
 102,
 120,
 120,
 120,
 98,
 120,
 102,
 102,
 102,
 120,
 98,
 98,
 120,
 102,
 120,
 98,
 102,
 120,
 120,
 120,
 102,
 98,
 120,
 102,
 98,
 120,
 120,
 120,
 98,
 98,
 102,
 120,
 102,
 120,
 120,
 102,
 102,
 120,
 102,
 102,
 102,
 120,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 102,
 98,
 120,
 120,
 98,
 98,
 120,
 102,
 120,
 98,
 98,
 120,
 120,
 102,
 120,
 102,
 120,
 98,
 102,
 102,
 98,
 115,
 120,
 98,
 102,
 102,
 120,
 98,
 98,
 98,
 98,
 120,
 120,
 115,
 102,
 120,
 102,
 120,
 102,
 120,
 120,
 120,
 98,
 120,
 102,
 120,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 120,
 120,
 98,
 120,
 98,
 102,
 120,
 98,
 98,
 120,
 102,
 120,
 98,
 102,
 98,
 98,
 98,
 102,
 120,
 98,
 120,
 98,
 102,
 120,
 120,
 120,
 102,
 120,
 102,
 98,
 98,
 120,
 98,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 98,
 120,
 115,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 98,
 102,
 120,
 120,
 120,
 120,
 98,
 120,
 120,
 120,
 98,
 120,
 120,
 98,
 98,
 102,
 98,
 120,
 98,
 120,
 98,
 98,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 98,
 98,
 120,
 98,
 120,
 120,
 120,
 102,
 102,
 120,
 102,
 115,
 102,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 120,
 98,
 115,
 120,
 120,
 120,
 98,
 98,
 120,
 98,
 102,
 115,
 120,
 115,
 102,
 102,
 98,
 98,
 120,
 102,
 120,
 102,
 120,
 120,
 120,
 102,
 102,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 98,
 102,
 102,
 120,
 120,
 102,
 120,
 120,
 102,
 120,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 98,
 120,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 102,
 102,
 120,
 102,
 120,
 98,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 102,
 120,
 102,
 120,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 98,
 120,
 102,
 102,
 120,
 120,
 102,
 120,
 120,
 102,
 120,
 98,
 120,
 120,
 120,
 102,
 102,
 102,
 98,
 102,
 102,
 120,
 98,
 102,
 120,
 102,
 98,
 120,
 120,
 102,
 120,
 120,
 102,
 120,
 120,
 102,
 102,
 102,
 120,
 120,
 120,
 102,
 120,
 102,
 120,
 102,
 120,
 98,
 120,
 120,
 102,
 102,
 120,
 102,
 120,
 120,
 120,
 102,
 120,
 120,
 120,
 120,
 120,
 120,
 102,
 102,
 102,
 120,
 102,
 98,
 102,
 ...]

----

In [37]:
target = []
data = []

for row_index, row in mr.iterrows() :
    target.append(row.loc[0])
    row_data = []
    for v in row.loc[1:]:
        row_data.append(ord(v))
    data.append(row_data)

In [43]:
data[:2]

[[120,
  115,
  110,
  116,
  112,
  102,
  99,
  110,
  107,
  101,
  101,
  115,
  115,
  119,
  119,
  112,
  119,
  111,
  112,
  107,
  115,
  117],
 [120,
  115,
  121,
  116,
  97,
  102,
  99,
  98,
  107,
  101,
  99,
  115,
  115,
  119,
  119,
  112,
  119,
  111,
  112,
  110,
  110,
  103]]

In [44]:
print(target[:2])

['p', 'e']

#### DataFrame 만들기

In [45]:
# Target을 기준으로 DataFrame 만들기
targetTemp = pd.DataFrame(target)
targetTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [47]:
# data를 dataframe으로 만들고 column 이름을 겹치지 않게 하기
dataTemp = pd.DataFrame(data)
dataTemp.rename(columns= lambda x : x + 1, inplace = True)
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [48]:
# 2개의 dataframe 합치기
mr2 = pd.concat([targetTemp, dataTemp], axis='columns')
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [49]:
mr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8124 non-null   object
 1   1       8124 non-null   int64
 2   2       8124 non-null   int64
 3   3       8124 non-null   int64
 4   4       8124 non-null   int64
 5   5       8124 non-null   int64
 6   6       8124 non-null   int64
 7   7       8124 non-null   int64
 8   8       8124 non-null   int64
 9   9       8124 non-null   int64
 10  10      8124 non-null   int64
 11  11      8124 non-null   int64
 12  12      8124 non-null   int64
 13  13      8124 non-null   int64
 14  14      8124 non-null   int64
 15  15      8124 non-null   int64
 16  16      8124 non-null   int64
 17  17      8124 non-null   int64
 18  18      8124 non-null   int64
 19  19      8124 non-null   int64
 20  20      8124 non-null   int64
 21  21      8124 non-null   int64
 22  22      8124 non-null   int64
dtypes: int64(22), object(1)
memory usage: 1.4+ MB

#### RandomForest로 분류하기

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [53]:
# data / target 분리
mr_data = mr2.iloc[:,1:]
mr_target = mr2[0]

print(mr_target)

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: 0, Length: 8124, dtype: object

In [54]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        mr_data,
        mr_target,
        random_state= 42,
        stratify= mr_target
    )

In [58]:

# 모델 생성
clf = RandomForestClassifier()

# 모델 학습
clf.fit(train_input, train_target)

# 검증
clf.score(test_input, test_target)

1.0

In [60]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

---
#### One-hot Encoding
- 숫자 데이터가 숫자로써 의미가 있으면 상관 없지만, 위의 데이터는 분류를 위한 데이터이므로 숫자 크기의 의미가 없다.

#### 연습

In [62]:
# 1번열
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [63]:
mr2[1].unique()

array([120,  98, 115, 102, 107,  99])

In [64]:
pd.get_dummies(
    data = dataTemp,
    columns = [1],
    prefix = '1'
)

,2,3,4,5,6,7,8,9,10,11,...,19,20,21,22,1_98,1_99,1_102,1_107,1_115,1_120
0,115,110,116,112,102,99,110,107,101,101,...,112,107,115,117,False,False,False,False,False,True
1,115,121,116,97,102,99,98,107,101,99,...,112,110,110,103,False,False,False,False,False,True
2,115,119,116,108,102,99,98,110,101,99,...,112,110,110,109,True,False,False,False,False,False
3,121,119,116,112,102,99,110,110,101,101,...,112,107,115,117,False,False,False,False,False,True
4,115,103,102,110,102,119,98,107,116,101,...,101,110,97,103,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,115,110,102,110,97,99,98,121,101,63,...,112,98,99,108,False,False,False,True,False,False
8120,115,110,102,110,97,99,98,121,101,63,...,112,98,118,108,False,False,False,False,False,True
8121,115,110,102,110,97,99,98,110,101,63,...,112,98,99,108,False,False,True,False,False,False
8122,121,110,102,121,102,99,110,98,116,63,...,101,119,118,108,False,False,False,True,False,False
8123,115,110,102,110,97,99,98,121,101,63,...,112,111,99,108,False,False,False,False,False,True

---

In [ ]:
# 적용
for i in range(1, 23):
    dataTemp =\
        pd.get_dummies(
            data = dataTemp,
            columns = [i],
            prefix = str(i)
        )

In [69]:
dataTemp.shape

(8124, 117)

In [70]:
mr3 = \
    pd.concat(
        [targetTemp, dataTemp],
        axis = 'columns'
    )
mr3.head()

,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,False,True,False
1,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,e,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
3,p,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
4,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False

In [75]:
train_input, test_input, train_target, test_target = \
    train_test_split(
        mr3.iloc[:, 1:],
        mr3[0],
        random_state= 42,
        stratify= mr3[0]
    )

In [76]:
# 모델 생성
clf = RandomForestClassifier()

# 모델 학습
clf.fit(train_input, train_target)

# 검증
clf.score(test_input, test_target)

1.0