In [1]:
import pandas as pd

In [ ]:
# 점수 입력
data = {
    '3P' : ,
}

df = pd.DataFrame(data)

----

In [ ]:
# 저장한 모델 불러오기
import joblib
knn = joblib.load("../Data/knn_basketball.h5")

In [ ]:
# 불러온 모델 이용한 예측
pred = knn.predict(df)
print(f"추천하는 포지션은 {pred[0]} 입니다.")

----
iris.csv를 학습하여 모델을 저장한다.
- svm(svm_iris.h5)
- randomForest(rf_iris.h5)
- knn(knn_iris.h5)

저장된 모델을 불러서 예측해보기
- SepalLength : 5.1
- SepalWidth : 3.0
- PetalLength : 1.3
- PetalWidth : 0.2

In [2]:
# 데이터 가져오기
iris_df = pd.read_csv('../Data/iris.csv')
iris_df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [8]:
# feature / target 분리
iris_data = iris_df.iloc[:, 0:-1]
iris_target = iris_df['Name']

In [9]:
# train / test dataset 구성
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = \
    train_test_split(
        iris_data,
        iris_target,
        random_state= 42,
        stratify= iris_target
    )

train_input.info()

<class 'pandas.core.frame.DataFrame'>
Index: 112 entries, 130 to 47
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  112 non-null    float64
 1   SepalWidth   112 non-null    float64
 2   PetalLength  112 non-null    float64
 3   PetalWidth   112 non-null    float64
dtypes: float64(4)
memory usage: 4.4 KB

In [12]:
# 모델 생성 (SVM, RF, kNN)
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

clf_svm = SVC()
clf_rf = RandomForestClassifier()
clf_knn = KNeighborsClassifier()

models = [clf_svm, clf_rf, clf_knn]
score = {}

for model in models :
    model.fit(train_input, train_target)
    score[model] = model.score(test_input, test_target)

print(score)

{SVC(): 0.9210526315789473, RandomForestClassifier(): 0.9210526315789473, KNeighborsClassifier(): 0.9736842105263158}

In [14]:
# 에측 데이터
data = {
    'SepalLength' : 5.1,
    'SepalWidth' : 3.0,
    'PetalLength' : 1.3,
    'PetalWidth' : 0.2
}

new = pd.DataFrame([data])
new

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.0          1.3         0.2

In [18]:
# 새로운 데이터 예측

for model in models:
    print(f"{model}, prediction : {model.predict(new)}")

SVC(), prediction : ['Iris-setosa']
RandomForestClassifier(), prediction : ['Iris-setosa']
KNeighborsClassifier(), prediction : ['Iris-setosa']